services:
  username_bot:
    container_name: deltachat_username_bot
    build: .
    init: true
    restart: always
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    volumes:
      - ./data:/app/data
      - ./data/usernamebot:/root/.config/usernamebot
    ports:
      - "127.0.0.1:8080:8080"
    environment:
      - PORT=8080
      - DC_DB_DIR=/app/data
      - DB_PATH=/app/data/username.db
      - BASE_URL=https://deltachat.id
      - INVITE_BASE_URL=https://i.deltachat.id/#
      - DISPLAY_NAME
      - STATUS_TEXT
      - AVATAR_PATH
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
